### ISSUE TITLE
Icon's on the EXTERN URL Buttons in the VPS Table AREA

### ISSUE THREAD

**Issue by wlan4you** [syd711/vpin-studio#114]
The Idea is, to bring on all EXT Downloadlink URL Buttons the small Icon.
Maybe you like it to bring them to all.
Dropbox you have make a small Icon...   :)

![Screenshot 2024-01-28 204018](https://github.com/syd711/vpin-studio/assets/60288714/a1afbac3-9ea0-403c-9570-78896ce23e0d)

Maybe this Colorcode for the https://vpuniverse.com/ Webseitelink.
The dominantcolor in the Forum and downloadarea there looks like this green:

RGB: 99 170 78
HEX: 63aa4e
CMYK: 66 8 68 0 %

![Screenshot 2024-01-28 201853](https://github.com/syd711/vpin-studio/assets/60288714/edd167ae-6539-4ec3-83b5-f7f5838b35a6)

![bitly com](https://github.com/syd711/vpin-studio/assets/60288714/2d4f387e-a00c-42c3-94fe-75ac94b7cb47)

![mega io](https://github.com/syd711/vpin-studio/assets/60288714/cf4e8a8c-01f1-4b33-83b2-8b02bb27d189)

![vpforums org](https://github.com/syd711/vpin-studio/assets/60288714/aff1d522-f3d8-42d2-899d-573a080db036)

![vpuniverse com](https://github.com/syd711/vpin-studio/assets/60288714/cb400fc2-ecd1-4b25-bed9-a38e053cb3a0)

![pinballnirvana com](https://github.com/syd711/vpin-studio/assets/60288714/9532e93d-bb1d-4740-96f1-7ebc8a07931f)

![ipdb org](https://github.com/syd711/vpin-studio/assets/60288714/47ccd447-0239-4709-af48-6dd713c93f9f)

**Comment by syd711** [comment]
I get the idea, but I'd like to close this ticket as a "won't fix". The reasons for this:
- Without the owner's consent there is always the risk of trade mark infringement.
- It introduces new colors which make the overall experience a bit more "turbulent".

The "clean" way to solve this would to use white icons for all logos, but the library I am using for this did only provide an icon for "dropbox", that's why its the only "real" logo here.

Regarding the original logos on the "Tables" tab: I made an exception here since both were open source projects and even if they don't match with the design, they massively help understanding the difference between these tabs.

**Comment by wlan4you** [comment]
Hey,
its ok.
It was an Idea.
It is YOUR VPIN-Studio   :)
Your VPIN-Studio, your Rules !!!

:)
