### ISSUE TITLE
Pause menu, automatic show Highscore on DMD and Youtube video instruction on BG

### ISSUE THREAD

**Issue by Kongedam** [syd711/vpin-studio#122]
**Describe the solution you'd like**

Instead of having a buttons in pause menu, then just show:
High Score Card on DMD and Video Instruction on BG

In Settings add the possibility to choose what YouTube video to use.
you can use the author name from VPS

Best regards
Michael Kongedam

**Comment by syd711** [comment]
> I still would like an option to autoplay it when entering the menu, without any buttons + show High Score on Full DMD screen 
> Further more the video on backglass should repeat when finish

**Comment by syd711** [comment]
I checked the repeat flag. As far as I can see, YouTube does not support this.

**Comment by Ltek** [comment]
I'd suggest a minor tweak... pull from the popper media (not YouTube videos).

Give the user a choice of what they want on what screen. For example, I'd want VPS's High Score Card on the FullDMD and the Table Instruction Card (Popper's Help image) on the Backglass

**Comment by syd711** [comment]
This issue should be solved with 2.15.0 where you can choose the pause menu style.

**Comment by syd711** [comment]
Since the Chrome in kiosk mode does not work in combination with some backglass videos, I switched to a windows mode where the user can position the screen based on a Popper screen.
This way, the video can be shown in a smaller scale centered on the backglass or on the topper.
@Kongedam It is not the solution we aimed for, but I hope this solution is suitable for you.

**Comment by syd711** [comment]
Fixed with 2.18.0
