### ISSUE TITLE
[Feature Request] Integrate VPX Preview Image

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#150]
very minor / not a must have but thought it was cool, just released... https://www.vpforums.org/index.php?app=downloads&showfile=18225

**Comment by syd711** [comment]
Pretty cool indeed! I did not have this screenshot field on my radar yet, but it would be a nice feature. I already read all other fields and display them in the "Script Data" section, but the screenshot is missing.

But the problem I have here is the same as for reading and writing VPX files. I'm still struggling with the binary data. E.g. I can already read the screenshot information, but the PNG is broken because of some invalid bytes. I have to dive deeper into that topic and hope to support both without additional tools: writing VPX files and reading the PNG screenshot info.

See also: https://github.com/syd711/vpin-studio/issues/140

**Comment by syd711** [comment]
I changed the title to make emphasize the aimed solution.

**Comment by syd711** [comment]
Added with 2.14.0
