### ISSUE TITLE
NVOffset 

### ISSUE THREAD

**Issue by yoshi98bc** [syd711/vpin-studio#161]
So when multiple tables use one rom, NVOffset is needed in the table script to keep high scores separate. Is vpin studio able to use these NVOffset files to keep high scores for multiple tables with the same rom?

Thanks

**Comment by syd711** [comment]
The nvoffset is used by VPX when writing the highscore into the nvram file, and it is checked by the VPin Studio to determine the correct nvram for the highscore extraction. So since tables writes their highscores in different nvrams using the same ROM, the scores are separated.

At least that's my understanding (iirc). But I haven't had a look on this for a long time and want to build a better support for it - e.g. a check if there is a matching nvram file available, including the option to support ROM aliases.
The ticket for this is here: https://github.com/syd711/vpin-studio/issues/137

I hope this anwers you question.

**Comment by yoshi98bc** [comment]
I just discovered NVoffset and am learning how it works. I wasnt sure if
your program is compatible with the way it works and if it could find the
high scores for games that share the same rom.

**Comment by syd711** [comment]
I hope I answered your question, so I close this ticket for now.
As already mentioned, by fixing the related ticket, I hope to better visualize the support for this too.
