### ISSUE TITLE
[Feature Request] Streamline UI workflow so ALL table edits/updates/changes on single window view

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#163]
Suggestion is to streamline workflow so ALL table edits/updates/changes can be viewed and accessed from the main screen / Table List. Thus Tables List as ALL abilities in a single view window as example mockup shows

That window has Tables on the left and associated info on the right; so add to that...

1. move each/all tabs from Table Data Manager to be separate drop-down on right-side with all the other drop-down sections

2. Integrate the "Asset Manager" separate window to not be separate. Make it a 'slide-open to the right' (see attached mockup) that is integrated, not separate. This eliminates the modal window and allows a user to quickly navigate the table selection - and can still use the drop-downs (if needed) while editing Assets.
<img width="2023" alt="Untitled" src="https://github.com/syd711/vpin-studio/assets/1626802/144ef962-99fa-4f50-be1d-6636b1f8a009">

**Comment by syd711** [comment]
> 1. move each/all tabs from Table Data Manager to be separate drop-down on right-side with all the other drop-down sections

I just moved "everything" into that dialog. The combination of the Spreadsheet, VPX and scanned data, distributed over the different collapsibles in the main view, made the data management hard to understand. Especially the auto-fill action. By consolidating this in one dialog, I hoped to make this easier for the user. I'm actually planning to move the alias mapping (and the nvoffset) there too (and rebuild it). I see the problem too that data is managed in the collapsible sections AND this dialog. So right now I'm a bit undecided which way to go and will consult with some interaction design collegues.

> 2. Integrate the "Asset Manager" separate window to not be separate. 

I like the idea. I get why the additional click is cumbersome. I'm thinking about a view-mode-switch so that the additional panel you mocked-up will move into the table view. I'll attach some mock-ups here.

**Comment by syd711** [comment]
Just a rough copy past concept. My idea is to provide a mode switch, so that the table overview toggles into a media asset management view.

![image](https://github.com/syd711/vpin-studio/assets/1169826/d75563ee-6fce-4fbe-85d0-c4519391dc7c)

**Comment by Ltek** [comment]
looks good. I'd suggest do that for the media assets and also any other modal windows you have, like...

![image](https://github.com/syd711/vpin-studio/assets/1626802/e0b16b25-fcd1-41c6-a939-17b956eb1b9e)

**Comment by syd711** [comment]
Released with 2.18.0
The new asset view should solve this issue now. 

As for the "Table Data Manager" dialog: I do not plan to embed this dialog somewhere because I think the final "Save" action is required here. And it combines too many aspects so I actually prefer it as it is.

I close the ticket for now.
