### ISSUE TITLE
[Feature Request] View and Edit Notes metadata field in VPX Tables display

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#209]
Would be nice to be able to quickly/easily see and update the metadata Notes from the main VPX Tables screen. 
For example, table media may be very are different and it would be nice to "remember" (aka, see the notes) for why some tables have FullDMD videos, others do not . Some have B2S, others do not. Etc

thx

**Comment by syd711** [comment]
I assume you mean the notes/meta-data read from the VPX file here? Yes, these fields are currently read-only in the script section, since I have no tool to write them back. I can talk to the **vpxtools** guy if he knows a way to do that.

**Comment by syd711** [comment]
I read the post too hasty this morning. You mean the "Notes" field from the Popper database, right? The only idea I have in mind is to add an additional context menu entry for this.

**Comment by Ltek** [comment]
yes, I thought we should leverage that existing field instead of creating a new one. these are to help the user remember what we did and why... "using XYZ version of table because ABC has lighting problems" , etc

**Comment by syd711** [comment]
As you can see, a similar idea came up.
I have cleared the "Notes" field, so that is not overwritten by the auto-fill function.
My idea is to utilize the status column for this and flag some keywords.

- if you use the **TODO** keyword inside the "Notes" field, you'll see a custom "Status" icon. This is something done by all developement tools. 
- A click on the status icon would open a smaller "Notes" window where you can edit the notes directly.
- An additional filter you show you all tables with open "TODOs".

**Comment by syd711** [comment]
Good points (mentioned in the other ticket)! So for the VPS ToDos I have an idea how to set them up. But I'm not sure about a good position to quick access the notes. Is a read-only view sufficient just to take a quick look on them? I'd suggest to add this data as tooltip for the status icon for the table name then.

**Comment by Ltek** [comment]
I didnt realize we could already see/edit the notes!

So... maybe just add the 'To-Do' checkmark/flag in the VPX Table grid with a mouse-over showing that... and if we want to edit the text, we can open the metadata as below...

![image](https://github.com/syd711/vpin-studio/assets/1626802/8b2425c8-9ed3-41d8-b132-26ea4f94f174)

**Comment by syd711** [comment]
Fixed with 2.20.0.
