### ISSUE TITLE
[Feature Request] Flag a table for to-do/follow-up

### ISSUE THREAD

**Issue by oper8r00** [syd711/vpin-studio#217]
**Is your feature request related to a problem? Please describe.**
I often find myself using VPIN Studio in a client/server mode because I don't like standing at my cab to do updates. As I'm doing updates to my cab, there are some that require me to be at the actual cab itself to verify something or make script changes and its frustrating that I have to write these "follow-up" activities on a separate sheet of paper.

**Describe the solution you'd like**
1. Allow the user to flag a table that requires follow-up
2. Allow the user to create some kind of note on table for the follow-up activitiy
3. Allow the user to remove the flag/note
5. Display an indicator on the table for if its been flagged
6. Remove the indicator once the follow-up has been closed/removed/deleted
7. (Nice to Have) Allow the user to filter on tables that have been flagged
8. (Nice to Have) Hover over the indicator to display the note

**Describe alternatives you've considered**
I've been using pencil & paper. There is a notes field in the Table Data Manager, but this may be overwritten with an auto-update?

**Additional context**

**Comment by Ltek** [comment]
@syd711 complimentary but not the same. Notes are permanent as they mainly function as a reminder of 'why' you did something... not just what you 'need to do'. 

The Todo is similar to the Popper WIP flag. I'd suggest having 2 items in VPS...
1. Popper's Noted field - tied to popper database
2. VPS specific ToDo flag -not- tied to Popper's WIP since popper' uses WIP to organize tables/games that need attention before having them part of your regular playlists -- thus they are not 'playable' in popper yet. VPS ToDo has a different purpose and should not be named or tied the Popper

**Comment by syd711** [comment]
Fixed with 2.20.0.
