### ISSUE TITLE
[Feature Request] Pause Menu shows High Score Card and Rules

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#229]
just thought it would be cool to have the Pause menu show the Rules (Help Card) and VPS High Score Card w/ Popper media as background for it. Prob stacked vertical.

**Comment by syd711** [comment]
Sure, I'll can add another view option for that.

**Comment by syd711** [comment]
I'm catching up on this. The pause menu is already showing the card and rules. So this is fixed?

**Comment by syd711** [comment]
As mentioned the Pause menu is already showing these two.
As an additional feature I'm thinking about providing a table menu that opens for the given selection in PinUP Popper after n seconds or via pause key. The menu would have the benefict of e.g. resetting highscores, since this at this time, the game is not started yet.

**Comment by Ltek** [comment]
> As mentioned the Pause menu is already showing these two. As an additional feature I'm thinking about providing a table menu that opens for the given selection in PinUP Popper after n seconds or via pause key. The menu would have the benefit of e.g. resetting highscores, since this at this time, the game is not started yet.

While that sounds good from an 'admin' standpoint, it lends itself to mischief... kids messing around, accidently clearing high scores, etc. If you want to have an option to select 'additional' information, or change "view styles" thats cool. Basically anything that can be undone from that same on-screen menu and is non-destructive / non-adminstrative
