### ISSUE TITLE
Metallica high score not recognized correct file?

### ISSUE THREAD

**Issue by ecchodun** [syd711/vpin-studio#268]
Is this one not supported?  The high scores showing in vpin-studio are not the ones in game.  Also, the nvram file mtl_180hc shows last updated today (when I got a high score)
![Metallica HS2](https://github.com/syd711/vpin-studio/assets/78839467/6527c4ba-0aa7-4b63-8c33-046a82300904)
 the attached are not the ones on the game itself?
![Metallica HS](https://github.com/syd711/vpin-studio/assets/78839467/9273e81e-3939-4e46-a631-851f95755c64)

**Comment by syd711** [comment]
I think this was was reported before somewhere on my Discord.
The ROM **mtl_180hc** is marked as supported from pinemhi, but does not work.
Iirc switch to ROM **mtl_180h** and it will work.

**Comment by ecchodun** [comment]
You mean switch the ROM in the high score data or in the table itself? I switched the ROM name above to mtl_180h and there's no change.  Still the error in my first attachment.

**Comment by syd711** [comment]
Sorry, I meant the ROM itself. I can ask on Discord again who did that change. But iirc you change the ROM name in the script to "mtl_180h", install the matching ROM and then it works.

**Comment by ecchodun** [comment]
But then I can't use the color ROM, no?

**Comment by syd711** [comment]
Unfortunately no. I rely here on pinemhi and have no influence about which ROM values can be read or not.
But did you tried it anyway?

**Comment by ecchodun** [comment]
I'm not sure I understand.  If I load the game with the "hc" add-on, and that game shows my high score, why can't vpin-studio be triggered from that same high score table?  If it's tied to the "h" rom, is there a way to allow the user to select the rom for the high score table of their choice?

**Comment by syd711** [comment]
Not sure I got the last part, so I'll explain how the highscore extraction works:

The ROM file only contains the "operating system" of the the table with all default values. When you create a highscore or change the settings of the table, these settings will be written into a .nv RAM file. Since every ROM file creates a different .nv RAM file, the tool **pinemhi.exe** must know every .nv file individually. So even the slightest change requires some change for a successful extraction of the highscore from the .nv RAM file.

I assume the developer of pinemhi thought that the generated .nv file for the colored Metallica ROM can be read the same way like the non-colored, which is not the case.

I hope I haven't bored you with too many technical details ;)

**Comment by ecchodun** [comment]
No, you didn't bore me.  :) So what you're saying is just the pinemhi software can't extract the high score data from the colored rom.  It otherwise has nothing to do with your vpin-studio processes?  That's too bad because my next question is what would make the colored rom high score table so different?  Is the Metallica colored rom one of a kind or have you found others like this (e.g., is it an issue with Stern colored roms)?  Thank you for the response.

**Comment by syd711** [comment]
This Metallica ROM is so far the only ROM where pinemhi says, that is is supported, but it does not work.
Of course, there may be more, but right now the tool support ~1200 tables, so ...

I sometimes check for updates on http://www.pinemhi.com/
Besides that, there is nothing I can do on my end, since I have no clue how to read the .nv files.

**Comment by ecchodun** [comment]
Thank you for taking the time for responding.  You can close this issue.
