### ISSUE TITLE
[Feature Request] Add Author Column (or filter?)

### ISSUE THREAD

**Issue by syd711** [syd711/vpin-studio#383]
> gorgatron — Yesterday at 7:32 AM
feature idea: i have certain favorite authors, e.g. VPW.  It would be nice if I could enter a list of them and filter down the VPS tables using that -- it would show all tables that match and indicate:

> the table has a version by one of these authors
i have the table (but maybe not from one of these authors)
i have the table and it is from one of these authors
maybe: there are additional versions from these authors that I don't have

> Anyway, I kind of manually do this by arrowing through or filtering on the website by author, but it is tedious to go through.  My goal is to find tables by authors that I like because maybe I want to upgrade the tables I have or add new tables/versions.
Even if I could search for all VPW tables (by author) and have it filter the tables/versions by authors this would be pretty useful I think.

**Comment by leprinco** [comment]
Working on it, I have 4 questions :

1) should I integrate the 'show Only installed Tables in the filter or leave it where it is ?
![383 question 01](https://github.com/user-attachments/assets/0eb21d48-3683-456f-b31a-be94d6339754)

2) should the filter also apply on the sidebar. If yes, suggest to grey out the other lines
Personnally I would like this
![383 question 02](https://github.com/user-attachments/assets/4ad290e4-2219-4ef8-9923-5727581a8cd1)

3) Should the author filter bring all tables authored by "author" or should the filter also consider authors of other assets
On below, screen If I type Ryguy417 in "author" criteria, this "Austin Power" will show too because he is an author of a backglass
Personnaly, I would go with this
![383 question 03](https://github.com/user-attachments/assets/58b08689-f156-4063-aebc-229dca15d270)

And 2 and 3) combined, if we filter sidebar too, should the other assets be filtered as well
Perso, I would say yes

Feel free to comment !

**Comment by leprinco** [comment]
Self answering question 3, will support both :
![image](https://github.com/user-attachments/assets/ea4a6397-72b6-421d-9427-61d0597de6dd)

**Comment by syd711** [comment]
As discussed on Discord, let's move everything to the fitler an filter all assets.

**Comment by gorgatron1** [comment]
> should I integrate the 'show Only installed Tables in the filter panel or leave it where it is on top ?

I think that makes sense.

> should the filter also apply on the sidebar. If yes, suggest to grey out the other lines

Yes, though you still want some indication of installed tables.  For example you are looking to see if there are VPW versions of tables that you have you need to see what you are searching for + what you have installed

> Should the author filter bring all tables authored by "author" or should the filter also consider authors of other assets

I think probably all of the assets.  There aren't so many tables and back glasses authored by the same people.  I wonder about POVs though -- I think those are _all_ by one person.

Thanks!

**Comment by leprinco** [comment]
First version committed, I'll add 2 new tickets, one for filtering on features, and one for "filtering" the sidebar. 
Done as part of this ticket :
- Added Filter panel in VPS, ability to filter on authors, manufacturer and them + presence of assets
- Added sorter on all column of VPS table
- Modificed count of installed tables to count only filtered ones

More technically :
- Moved the detection of installed flag from VpsTableEntry into controller, in a dedicated thread as it calls getGamesCached(), so was blocking UI
- Added VpsTableModel to hold the install flag and avoid multiple service call (better even if it were leveraging cache)
- Reworked the BaseLoadingModel to move more code in it, simplifying code in TableOverviewController and BackglassManagerController
- Added BaseLoadingColumn to share code and simplify configuration of TableColumn
- Added the JFXFuture utilities
- Added a WaitOverlay utilities

**Comment by syd711** [comment]
Fixed with 3.4.0
