### ISSUE TITLE
Check highscores

### ISSUE THREAD

**Issue by syd711** [syd711/vpin-studio#403]
Some are known to work, but some I did not install yet:

Diner, Tom & Jerry, The Simpsons (2003), Transporter the Rescue (Midway 1989), Jurassic Park (Data East 1993), MF Doom (Original 2024), Star God (Zaccaria 1980), Star Wars (Data East 1992), Monster Bash (Williams 1998), Iron Man Vault Edition (Stern 2010), Ghostbusters (Limited Edition) (Stern 2016), Bad Cats (Williams 1989), Evel Knievel (Bally 1977), Space Mission (Williams 1976), Bronco (Gottlieb 1977)

**Comment by DoXer67** [comment]
[vpin-studio-logs.zip](https://github.com/user-attachments/files/16736368/vpin-studio-logs.zip)

**Comment by DoXer67** [comment]
After restart most tables are working now
Bad Cats: Changed NVRAM-Name from BVATS_I5 to BCATS_I5. I don't know, why the wrong name was parsed, I didn't edited it manually.
Hurricane: I reseted again the highscores, hope it's working now
Evel Knievel: I reseted again the highscores, hope it's working now
Iron Man (Vault Edition): Changed NVRAM-Name from IM183 to IM185VE. Similar to Bad Cats
Monster Bash: I reseted again the highscores, hope it's working now
Space Mission: Missing TXT-file, because because VPIN deletes the file after resetting the highscores. This should maybe fixed. I edited the file manually to reset the highscores.
The Simpsons: I reseted again the highscores, hope it's working now

Except the following:

1. Ghostbusters - Message: NVRAM spagb_100.nv not supported by PIMenHI. The file exists on disk, but with 0 bytes
2. MFDOOM - Set in VPINStudio to nvram-file MFDOOM, but no NVRAM-File on disk after playing this table
3. Star God - NVRAM stargoda.nv not supported by PIMenHI, exist on disk.
4. Star Wars (1992) - NVRAM stwr_107.nv not supoorted by PIMenHI, exists on disk.
5. Tom & Jerry - VPINStudio-message "Unknown Status".

**Comment by syd711** [comment]
We fixed Tom&Jerry

MFDOOM: You have to create a highscore so that the data is created.
I edited the script and set the scores to 0.
After that, the highscore was created and read.

The other tables are not supported by pinemhi which is used to extract the scores. So there is nothing I can do about them.
