### ISSUE TITLE
[Feature Request] built-in Monospaced fonts and 1-click All Template Font Update

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#460]
2 items...

Built-in Fonts... Finding fonts that look right for High Scores is not easy. It would be great to have a small set of built-in Monospaced fonts. Windows only includes 2, but others exist 

1-Click font update.... set a "global font with a way to change all/selected templates with 1 click.

**Comment by syd711** [comment]
The build in fonts are tricky, since the need to be installed for the server and also for the client which again might be Linux or MacOS. At least with 3.6.0 the true-type-font support has been improved so that more fonts are properly rendered.

I have added the "apply to all" button which will come with the next regular update.

**Comment by syd711** [comment]
Fixed with 3.7.0
