### ISSUE TITLE
[Bug] Improve VPX Emulator Check

### ISSUE THREAD

**Issue by syd711** [syd711/vpin-studio#547]
>Elicend — Yesterday at 10:13 PM
Hello
One request I have vpx 10.7 and vpx 10.8 I can record tables on one or other but when I chose all vpx table I have same result than visual pinball x which is 10.7 and no table from 10.8 and to see them I need to chose vpinball 10.8
For 10.8 it is good for 10.7 it is visual pinball x which is good but all vpx tables should have both no?

Our emulator check needs to be improved here. We check the emulator type by it's name, but we need to look at the file suffix .vpx here too. 

![image](https://github.com/user-attachments/assets/b1e0efda-bda4-4cfc-a5d0-900bf31792a3)

**Comment by leprinco** [comment]
fixed in 3.8 for popper emulator, not needed for others
Also refactored the concept of EmulatorType, by fully moving the responsibility of the detection of the Emulator type within the connector. As in pinballX the emulator are 'typed' and for standalone, only one VPX emulator is created, this bug was popper specific

**Comment by syd711** [comment]
Fixed with 3.8
