### ISSUE TITLE
Fullscreen Loading Videos

### ISSUE THREAD

**Issue by brentgl** [syd711/vpin-studio#582]
Hi

I saw this was previously an issue but was fixed but.....
After I add a blank for the loading then add the fullscreen one with Append
it just adds it with an 01 at the end and no option to choose eg 3 playfield.
I am currently renaming the second one and adding (SCREEN3) in my case but thought it would offer me a location

Thanks
Brent

**Comment by syd711** [comment]
I think there is a refresh bug in the list. Close the dialog or press reload, then the second asset appears. I've used this feature the last day, but noted this issue when used the first time.

**Comment by brentgl** [comment]
My second asset appears ok - just with an 01

![image_2024-11-07_132542994](https://github.com/user-attachments/assets/694521e0-c332-4d97-9a81-dfc00b5129ad)


I have to rename that file and add (SCREEN3) to the end for it to work
I thought it would be like pinup popper media where it asks me to assign a location

**Comment by syd711** [comment]
I've re-read your initial message and didn't understand this message:
> After I add a blank for the loading then add the fullscreen one with Append

I assume you've added a blank screen manually? The special behaviour of the loading screen view in the studio is that you can download a fullscreen loading video and press the the "Fullscreen" button. This will add a blank video so that the fullscreen loading video is actually played in fullscreen.

The "fullscreen" button is only available for the loading view and only enabled where there is one video without a "SCREEN" name.

![image](https://github.com/user-attachments/assets/5005aa73-9733-4786-ac28-a6331631a644)
