### ISSUE TITLE
Cloned table gets 0 rating instead of null

### ISSUE THREAD

**Issue by francisdb** [syd711/vpin-studio#6]
I cloned a table by uploading a new vpx and now it has a zero rating instead of no rating

**Comment by syd711** [comment]
I don't copy the table metadata yet, but will take care of that.

**Comment by syd711** [comment]
FYI: unfortunately I haven't my cab at home but can only work on it from time to time. That's why I often can't use my own software so much :(

**Comment by francisdb** [comment]
Strange that it gets a 0 if you don't copy. Not a big deal though.

**Comment by syd711** [comment]
I haven't checked, I assumed that's the problem but will take a look anyway.

**Comment by syd711** [comment]
Ok, I did clone the metadata, but null Integer values have been defaulted to "0".
Fixed with 1.3.4

**Comment by francisdb** [comment]
Mind linking a commit to all these fixes? Did you forget to push?

**Comment by syd711** [comment]
I'm currently working on a feature branch where I fix these issues too.
The specific commit for this ticket should be this: 
https://github.com/syd711/vpin-studio/commit/15d85cadb15e91e0a52822682b7a9c0d5b8667b2

Since your tickets are the first one on github, I'm still figuring out the process.
Ususally the bug reports where dropped via my Discord server which is linked in the settings of the Studio.
And usually the users haven't developed a deeper interest in the code ;)
