### ISSUE TITLE
[Bug] Highscore not found, when changed folder path

### ISSUE THREAD

**Issue by kleinrechner** [syd711/vpin-studio#678]
Folder of nvram has been changed ad registry, highscore nvram can not be found.

At windows registry Computer\HKEY_CURRENT_USER\SOFTWARE\Freeware\Visual PinMame\globals the path of nvram_directory has been changed to d:\vPinball\, vpin system files are still c:\vPinball

![image](https://github.com/user-attachments/assets/d0b3c4a4-bbba-48e4-bc7b-6c0729d4875b)

at Data Manager the rom and nvram can be found.
![image](https://github.com/user-attachments/assets/bac93303-281b-4e51-9081-8cae59d3b527)

but nvram of highscrore can not be found.

![image](https://github.com/user-attachments/assets/247ca583-efe0-4c23-ac83-9a0b897dc685)

At test environment, when the folder has not been changed, it is working.

 - OS: Windows 10
 - Version 3.11.1

**Comment by syd711** [comment]
A bug indeed. Right now the folder is assumed to be under the MAME folder and the registry entries are ignored.
I'm curious: you changed the folder yourself?

**Comment by Christian-Fluhrer** [comment]
Yes, I changed the registry entries by myself.

My registry entries are looking like here:
![image](https://github.com/user-attachments/assets/32e35ccd-f84f-4dd7-af24-ca58a4acab9d)

I don't know if that is also helpfull for you, I have also changed the pathes at the emulator settings:
![image](https://github.com/user-attachments/assets/fe0719b2-0973-4bc3-b6ab-d633beb4a560)

**Comment by syd711** [comment]
Fixed, comes with the next release.

- **Emulator Detection**: The way the **nvram** and **rom** folders are read has been changed. For VPX emulators...
  - the **nvram** folder is read from the Windows registry first, instead of simply assuming the default folder of PinMAME which is used as fallback now.
  - the **roms** folder is read from the frontend/Popper first. If the value is empty there or invalid, the Windows registry value for PinMAME roms is used instead.

**Comment by kleinrechner** [comment]
I updated to 3.11.2 and get a lot more problems because of the changed folder. Thats why I reseted everything to the default folder path and created hard links from the second hard drive to the default folders.
