### ISSUE TITLE
Loading screen size wrong after cloning a table

### ISSUE THREAD

**Issue by francisdb** [syd711/vpin-studio#7]
Not sure how this happens. If I remember correctly the table had a proper loading video and after the clone it looks like this.

![image](https://github.com/syd711/vpin-studio/assets/161305/a6885b30-f62a-4e08-9b4a-8e8b3ac9f943)

Even after removing and adding the loading screen I still get this wrong size. Not sure how to fix this on the popper side.

**Comment by syd711** [comment]
You use a blank default video an a second video with "(SCREEN3)" suffix. I wasn't aware of that recently. I assume that I skip the suffixed marked videos, that's why the full screen information get's lost.

As a workaround you can edit the loading video settings with the VPin Studio: open the edit dialog in media section, remove all other videos than the correct one. The "Full Screen" button should be enabled then and fix the problem. 

I'll check why the resources are not copied correctly.

**Comment by francisdb** [comment]
I can confirm clicking fullscreen and then removing the non `(SCREEN3)` entry fixes the issue.

**Comment by syd711** [comment]
Fixed with 1.3.4
Previous versions only supported one media asset for every screen. The change to multiple assets has not been applied to the media cloning.

https://github.com/syd711/vpin-studio/commit/d957503d7e925a5b306862826d56bc3c685a9f3c
