### ISSUE TITLE
New highscore-card after exit table

### ISSUE THREAD

**Issue by GerhardPK** [syd711/vpin-studio#77]
After the update to 2.7, creating of  cards works fine. I integrated the cards into “game help” and assigned the hey “H” in Popper’s controller setup. However, it seems that the maps are not updated after the end of the table. The new high score only appears after “rescan”.

My son set up PINemHi for me in future pinball, it works great there. After a few seconds the current video appears.
thats my close script in VPX
"[STARTDIR]LAUNCH\PUPCLOSER.EXE" WINTIT "Visual Pinball" 10 1 

REM Generate HiScore media file
"c:\VPinball\PinemHi\hiscore.bat" [?ROM?] "[GAMENAME]" "[?GAMETYPE?]"

curl -X POST --data-urlencode "table=[GAMEFULLNAME]" http://localhost:8089/service/gameExit

Gerhard Krill

**Comment by syd711** [comment]
Note that the highscore card is only generated a few seconds AFTER the table has been exited.
If you generated a new highscore and immediately show the highscore card, it won't be rergenerated - only after exit.
(It is not possible to determine when a VPX game ends, that's why it works this way).

If you exited the table:
Did this happen for a specific table or for different ones? I'll check this again this evening.
Can you tell me the table name and also append the server log file here? From there I should be able to read what happend after the table exit.

**Comment by syd711** [comment]
Ok, I just noticed the same issue on my cabinet. I'll fix this asap.

**Comment by syd711** [comment]
I picked the wrong name for the card generation.
The fix comes with 2.8.0
